#!/bin/sh
# lib/ish.sh — iSH platform detection, backups, and auto-launch wiring.
#
# iSH always starts as root running /bin/sh -l, and there is no login manager to
# configure. The only reliable hook is /etc/profile. Because a bad edit here can
# make the app unusable, everything in this file is defensive:
#
#   * the injected block is delimited by markers and replaced wholesale on rerun
#   * /etc/profile is backed up before the first edit
#   * the switch only fires for an interactive root shell
#   * `su` is NOT exec'd, so a broken zsh drops back to a working root shell
#   * a disable file provides an escape hatch that needs no environment variable
#
# shellcheck disable=SC2034  # globals below are read by other modules
# Globals owned by this file:
#   BACKUP_DIR   timestamped directory holding copies of every file touched
#   ISH_CONFIGURED  1 once the /etc/profile block is in place

ISH_MARK_BEGIN="# >>> ish-setup >>>"
ISH_MARK_END="# <<< ish-setup <<<"
ISH_DISABLE_FILE="/etc/ish-setup/disable-autologin"
ISH_PROFILE_PATH="${ISH_PROFILE_PATH:-/etc/profile}"
BACKUP_DIR=""
ISH_CONFIGURED=0

# backup_init — create this run's backup directory.
backup_init() {
    BACKUP_DIR="$HOME/ish-setup/backups/$(date '+%Y%m%d-%H%M%S' 2>/dev/null || echo run)"
    mkdir -p "$BACKUP_DIR" 2>/dev/null || BACKUP_DIR=""
}

# backup_file — copy a file into the backup directory, preserving its path.
# A no-op when the file does not exist. Arguments: $1 absolute path.
backup_file() {
    [ -e "$1" ] || return 0
    [ -n "$BACKUP_DIR" ] || return 0
    _dest="$BACKUP_DIR$(dirname "$1")"
    mkdir -p "$_dest" 2>/dev/null || return 1
    cp -a "$1" "$_dest/" 2>/dev/null && log_write INFO "backed up $1"
    return 0
}

# ish_detect — confirm we are running under iSH.
# Returns: 0 confirmed, 1 probably not iSH.
ish_detect() {
    [ -d /proc/ish ] && return 0
    [ "$(uname -m 2>/dev/null)" = "i686" ] && return 0
    return 1
}

# ish_is_root — confirm the effective uid is 0. Returns: 0 if root.
ish_is_root() {
    [ "$(id -u 2>/dev/null)" = "0" ]
}

# ish_has_network — cheap reachability check against the Alpine mirrors.
# Returns: 0 if the package index can be fetched.
ish_has_network() {
    apk update >/dev/null 2>&1 && return 0
    if command -v wget >/dev/null 2>&1; then
        wget -q -T 8 -O /dev/null https://dl-cdn.alpinelinux.org/alpine/ 2>/dev/null && return 0
    fi
    return 1
}

# ish_configure_autologin — install the /etc/profile launch block.
# Arguments: $1 username to launch as.
# Returns: 0 on success.
ish_configure_autologin() {
    _user=$1
    # Overridable so the block can be generated against a scratch file
    # during testing without touching the real /etc/profile.
    _profile=${ISH_PROFILE_PATH:-/etc/profile}

    step_start "Configuring iSH launch"

    if [ ! -f "$_profile" ]; then
        : >"$_profile" 2>/dev/null || {
            step_fail "Configuring iSH launch" "cannot write $_profile"
            return 1
        }
    fi

    backup_file "$_profile"

    # Strip any previous block so reruns replace instead of stacking.
    if grep -qF "$ISH_MARK_BEGIN" "$_profile" 2>/dev/null; then
        _tmp="$_profile.ish-setup.$$"
        sed "/$(printf '%s' "$ISH_MARK_BEGIN" | sed 's/[]\/$*.^[]/\\&/g')/,/$(printf '%s' "$ISH_MARK_END" | sed 's/[]\/$*.^[]/\\&/g')/d" \
            "$_profile" >"$_tmp" 2>/dev/null && mv "$_tmp" "$_profile"
        rm -f "$_tmp" 2>/dev/null
    fi

    mkdir -p "$(dirname "$ISH_DISABLE_FILE")" 2>/dev/null

    cat >>"$_profile" <<PROFILE_BLOCK
$ISH_MARK_BEGIN
# Launch iSH directly into '$_user' running zsh.
#
# To get a root shell again, create the disable file from any shell:
#     sudo touch $ISH_DISABLE_FILE
# or launch with ISH_SETUP_SKIP=1 in the environment.
#
# This block is regenerated by ish-setup on every run. Edits are not preserved.
if [ "\$(id -u)" = "0" ] \\
   && [ -z "\${ISH_SETUP_SKIP:-}" ] \\
   && [ ! -f "$ISH_DISABLE_FILE" ]; then
    case "\$-" in
        *i*)
            if id "$_user" >/dev/null 2>&1 && [ -x /bin/su ]; then
                # Deliberately not exec'd: if the login fails, or zsh is broken,
                # control returns here and you keep a usable root shell.
                su - "$_user"
                _ish_rc=\$?
                if [ "\$_ish_rc" -eq 0 ]; then
                    exit 0
                fi
                printf 'ish-setup: could not start a session for %s (exit %s).\\n' \\
                    "$_user" "\$_ish_rc"
                printf 'ish-setup: continuing as root.\\n'
                unset _ish_rc
            fi
            ;;
    esac
fi
$ISH_MARK_END
PROFILE_BLOCK

    if grep -qF "$ISH_MARK_BEGIN" "$_profile" 2>/dev/null; then
        # Syntax-check the result. A broken /etc/profile is the one edit that
        # can genuinely brick the app, so restore the backup if it will not parse.
        if sh -n "$_profile" 2>/dev/null; then
            ISH_CONFIGURED=1
            step_ok
            return 0
        fi
        ui_error "Generated /etc/profile did not parse. Restoring backup."
        [ -n "$BACKUP_DIR" ] && cp -a "$BACKUP_DIR$_profile" "$_profile" 2>/dev/null
    fi

    step_fail "Configuring iSH launch" "the launch block could not be installed"
    return 1
}

# ish_hostname — read a display hostname, falling back to something sensible.
ish_hostname() {
    hostname 2>/dev/null || cat /etc/hostname 2>/dev/null || printf 'ish'
}
